name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Setup build environment
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          API_BASE: ${{ secrets.API_BASE }}
        run: eval "echo \"$(cat src/environments/environment.ts)\"" > src/environments/environment.ts

      - name: Build Angular app
        run: npm run build --prod

      - name: Transfer files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ./dist/ng-file-explorer/*
          target: /var/www/ngfe
          rm: true
          strip_components: 2

      - name: Reload NGINX
        run: |
          mkdir ~/.ssh
          echo "$ssh_key" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo systemctl reload nginx"
        env:
          ssh_key: ${{ secrets.SSH_KEY }}
